../a xbh | tee -a OUTPUT
../a xbi | tee -a OUTPUT
../a xbj | tee -a OUTPUT
../a xbk | tee -a OUTPUT
../a xbl | tee -a OUTPUT
../a xbm | tee -a OUTPUT
../a xbn | tee -a OUTPUT
../a xbo | tee -a OUTPUT
../a xbp | tee -a OUTPUT
../a xbq | tee -a OUTPUT
../a xbr | tee -a OUTPUT
../a xbs | tee -a OUTPUT
../a xbt | tee -a OUTPUT
../a xbu | tee -a OUTPUT
../a xbv | tee -a OUTPUT
../a xbw | tee -a OUTPUT
../a xbx | tee -a OUTPUT
../a xby | tee -a OUTPUT
../a xbz | tee -a OUTPUT
../a xca | tee -a OUTPUT
../a xcb | tee -a OUTPUT
../a xcc | tee -a OUTPUT
../a xcd | tee -a OUTPUT
../a xce | tee -a OUTPUT
../a xcf | tee -a OUTPUT
../a xcg | tee -a OUTPUT
../a xch | tee -a OUTPUT
../a xci | tee -a OUTPUT
../a xcj | tee -a OUTPUT
../a xck | tee -a OUTPUT
../a xcl | tee -a OUTPUT
../a xcm | tee -a OUTPUT
../a xcn | tee -a OUTPUT
../a xco | tee -a OUTPUT
../a xcp | tee -a OUTPUT
../a xcq | tee -a OUTPUT
../a xcr | tee -a OUTPUT
../a xcs | tee -a OUTPUT
../a xct | tee -a OUTPUT
../a xcu | tee -a OUTPUT
../a xcv | tee -a OUTPUT
../a xcw | tee -a OUTPUT
../a xcx | tee -a OUTPUT
../a xcy | tee -a OUTPUT
../a xcz | tee -a OUTPUT
../a xda | tee -a OUTPUT
../a xdb | tee -a OUTPUT
../a xdc | tee -a OUTPUT
../a xdd | tee -a OUTPUT
../a xde | tee -a OUTPUT
../a xdf | tee -a OUTPUT
../a xdg | tee -a OUTPUT
../a xdh | tee -a OUTPUT
../a xdi | tee -a OUTPUT
../a xdj | tee -a OUTPUT
../a xdk | tee -a OUTPUT
../a xdl | tee -a OUTPUT
../a xdm | tee -a OUTPUT
../a xdn | tee -a OUTPUT
../a xdo | tee -a OUTPUT
../a xdp | tee -a OUTPUT
../a xdq | tee -a OUTPUT
../a xdr | tee -a OUTPUT
../a xds | tee -a OUTPUT
../a xdt | tee -a OUTPUT
../a xdu | tee -a OUTPUT
../a xdv | tee -a OUTPUT
